#!/bin/sh

cd "$(dirname "$0")"
cd ..

BRANCH=gh-pages
BUILDDIR=_build/html
COMMITMSG="Built public documentation"

git rev-parse --verify HEAD >/dev/null || exit 1

set -e

# Make sure we have the gh-pages branch locally
if [ ! $(git branch -l | grep ' gh-pages$') ]; then
  git fetch origin
  git checkout -b $BRANCH origin/$BRANCH
  git checkout master
fi

# Build site (generates pages in $BUILDDIR)
make html
touch "${BUILDDIR}/.nojekyll"

# Add built content to index, regardless of .gitignore settings
git add -f "$BUILDDIR"

# Write tree object from $BUILDDIR
TREE=$(git write-tree --prefix "$BUILDDIR")

# Create new commit with tip of $BRANCH as parent
COMMIT=$(echo "$COMMITMSG" | git commit-tree "$TREE" -p "$BRANCH")

# Update $BRANCH to point to new commit
git branch -f "$BRANCH" "$COMMIT"

# Remove staged changes from index
git reset -q -- "$BUILDDIR"
